---
# This task will make sure that /var/log will be mounted on a tmpfs device
# to prevent high write loads on the SD card of the raspberry.

- name: Ensure that tmpfs mountpoint for /var/log exists
  become: yes
  lineinfile:
    path: /etc/fstab
    regexp: '^.*/var/log.*'
      #    insertafter: '^tmpfs'
    insertafter: '^proc'
    line: tmpfs  /var/log    tmpfs  defaults,noatime,nosuid,mode=0755,size=100m  0  0
