---
# Install log2ram to prevent hammering the SD card with log messages
# and to extend its life. Hopefully.

- name: Disable and stop log2ram service (if running)
  become: yes
  systemd:
    name: log2ram
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Add log2ram sources.list file
  become: yes
  shell: echo "deb http://packages.azlux.fr/debian/ buster main" | sudo tee /etc/apt/sources.list.d/azlux.list

- name: Add log2ram GPG key to apt
  become: yes
  shell: wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -

- name: Update log2ram via apt
  become: yes
  apt:
    name: log2ram
    update_cache: yes

- name: Copy log2ram.conf configuration file
  become: yes
  copy:
    src: files/log2ram.conf
    dest: /etc/log2ram.conf
    mode: 0644

- name: Enable and start log2ram service
  become: yes
  systemd:
    name: log2ram
    enabled: yes
    state: started