---
# This task installs shairport-sync as described in
# https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md
#
# Variables used in this task are set in the group_vars/speakers file.

- name: Stop shairport-sync service (if any)
  become: yes
  systemd:
    name: shairport-sync
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Set shairport-sync device name
  set_fact:
    shairport_name: "{{ ansible_hostname | title }}"

- name: Turn off WiFi power management
  become: yes
  shell: iwconfig wlan0 power off

- name: Turn off WiFi power management (in /etc/network/devices)
  become: yes
  lineinfile:
    create: yes
    line: 'wireless-power off'
    path: '/etc/network/interfaces'
    state: present

# Perform apt update
- name: Install/update apt packages needed by shairport-sync
  become: yes
  apt:
    name: "{{ shairport_packages }}"
    state: present
    update_cache: yes

- name: Create "{{ shairport_local_dir }}"
  become: yes
  file:
    path: "{{ shairport_local_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Clone shairport-sync release "{{ shairport_release }}" to "{{ shairport_local_dir }}"
  become: yes
  git:
    repo: "{{ shairport_repository }}"
    dest: "{{ shairport_local_dir }}"
    clone: true
    update: true
    force: yes
    version: "{{ shairport_release }}"
  register: repository

- name: Run autoreconf
  become: yes
  command: autoreconf -fi
  args:
    chdir: "{{ shairport_local_dir }}"
  when: repository.changed

# If you need ALAC support you should read this first:
# https://github.com/mikebrady/alac
- name: Configure shairport-sync
  become: yes
  command: ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd
  #command: ./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd --with-apple-alac
  args:
    chdir: "{{ shairport_local_dir }}"
  when: repository.changed

- name: Build shairport-sync
  become: yes
  make:
    chdir: "{{ shairport_local_dir }}"
  when: repository.changed

- name: Install shairport-sync
  become: yes
  make:
    chdir: "{{ shairport_local_dir }}"
    target: install
  when: repository.changed

- name: Write shairport-sync configuration file
  become: yes
  template:
    src: shairport-sync.conf.j2
    dest: /etc/shairport-sync.conf
    owner: root
    group: root
    mode: 0644

- name: Enable shairport-sync service
  become: yes
  systemd:
    name: shairport-sync
    enabled: yes
    state: started

# EOF