---
# This task writes shairport-sync.config
- name: Set shairport-sync device name
  set_fact:
    shairport_name: "{{ ansible_hostname | title }}"

- name: Write shairport-sync configuration file
  become: yes
  template:
    src: shairport-sync.conf.j2
    dest: /etc/shairport-sync.conf
    owner: root
    group: root
    mode: 0644

- name: Restart shairport-sync service
  become: yes
  systemd:
    name: shairport-sync
    enabled: yes
    state: restarted