- name: Create local user account on Airplay device
  hosts: all
  remote_user: pi
  gather_facts: no
  any_errors_fatal: yes



  vars_prompt:
    - name: "username"
      prompt: "Username of user to create"
      private: no



  tasks:
    - name: Remove user (if present)
      user:
        name: "{{ username }}"
        state: absent
        force: yes
        remove: yes
      become: yes

    - name: Create new user
      user:
        name: "{{ username }}"
        shell: /bin/bash
        groups: adm, dialout, cdrom, sudo, audio, video, plugdev, games, users, input, netdev, gpio, i2c, spi
        append: yes
      become: yes

    - name: Create .ssh directory in user's home dir
      file:
        path: /home/{{ username }}/.ssh
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      become: yes

    - name: Check if playbooks/files/authorized_keys exists
      local_action: stat path=files/authorized_keys
      register: authorized_keys

    - name: Handle situation that file does not exist
      block:
      
        - name: Inform user that cannot continue if authorized_keys does not exist
          debug:
            msg: "Stop playbook because authorized_keys does not exist. Please create file first in playbooks/files/!"
      
        - meta: end_play
      
      when: authorized_keys.stat.exists == False

    - name: Copy playbooks/files/authorized_keys file to new user's ~/.ssh directory
      copy:
        src: files/authorized_keys
        dest: /home/{{ username }}/.ssh/authorized_keys
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644
      become: yes
      when: authorized_keys.stat.exists

    - name: Remove user from sudoers (if existing)
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: absent
        regexp: '^{{ username }}'
        validate: 'visudo -cf %s'

    - name: Add user to sudoers
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
