- name: Update RaspberryPi Airplay Devices
  hosts: all

  pre_tasks:
    - name: Check for Ansible version > 2.4
      assert:
        that: "ansible_version.full is version_compare('2.4', '>=')"
        msg: "This playbook requires Ansible version 2.4 or greater."

  tasks:
    - name: Get old Linux kernel version
      shell: uname -r
      register: old_kernel

    # Update the RPi's firmware using the rpi-update script
    - name: Update RaspberryPi firmware
      become: yes
      shell: rpi-update
      register: firmware
      ignore_errors: yes
      environment:
        SKIP_WARNING: 1


    - name: Fix any local configuration issues (if any)
      become: yes
      shell: dpkg --configure -a

    - name: Update apt sources
      become: yes
      shell: apt update

    - name: Update all packages via apt
      become: yes
      shell: apt dist-upgrade -y --fix-missing

    - name: Cleanup apt
      become: yes
      shell: apt autoremove -y


    - name: Run shairport-sync task to update repository
      include_tasks: "tasks/shairport-sync.yml"


    # Restart the devices only if new Linux kernel or new software has been installed
    - name: Reboot device
      include_tasks: "tasks/reboot.yml"


    # Get the new Linux kernel version if an update has been installed
    - name: Get new Linux kernel version
      shell: uname -r
      register: new_kernel
      when: firmware.stdout.find("already up to date") == -1

    - name: Linux kernel
      debug:
        msg: "Updated Linux kernel version {{ old_kernel.stdout }} to version {{ new_kernel.stdout }}"
      when: firmware.stdout.find("already up to date") == -1

    - name: Linux kernel
      debug:
        msg: "Unchanged Linux kernel version {{ old_kernel.stdout }}"
      when: firmware.stdout.find("already up to date") != -1

