- name: Update RaspberryPi Airplay Devices
  hosts: all

  pre_tasks:
    - name: Check for Ansible version > 2.4
      assert:
        that: "ansible_version.full is version_compare('2.4', '>=')"
        msg: "This playbook requires Ansible version 2.4 or greater."

  tasks:
    - name: Modify fstab to log to tmpfs
      include_tasks: "tasks/fstab.yml"

    - name: Install apt packages
      include_tasks: "tasks/apt.yml"

    - name: Run shairport-sync task to update repository
      include_tasks: "tasks/shairport-sync.yml"

    - name: Update cronjob
      include_tasks: "tasks/cronjob.yml"


    # Restart the devices
    - name: Reboot device
      include_tasks: "tasks/reboot.yml"

# EOF
