- name: Update settings on RaspberryPi Airplay Devices
  hosts: all
  gather_facts: no

  pre_tasks:
    - name: Check for Ansible version > 2.4
      assert:
        that: "ansible_version.full is version_compare('2.4', '>=')"
        msg: "This playbook requires Ansible version 2.4 or greater."

  tasks:
    - name: Copy authorized_keys
      include_tasks: tasks/copy-authorized_keys.yml
      
    - name: Update cronjob
      include_tasks: tasks/cronjob.yml

    - name: Update ALSA settings
      include_tasks: tasks/alsa.yml

# EOF