- name: Update settings on RaspberryPi Airplay Devices
  hosts: all
  gather_facts: no

  pre_tasks:
    - name: Check for Ansible version > 2.3
      assert:
        that: "ansible_version.full is version_compare('2.3', '>=')"
        msg: "This playbook requires Ansible version 2.3 or greater."

  tasks:
    - name: Check if playbooks/files/authorized_keys exists
      local_action: stat path=files/authorized_keys
      register: authorized_keys

    - name: Copy playbooks/files/authorized_keys file to .ssh directory
      copy:
        src: files/authorized_keys
        dest: ~/.ssh/authorized_keys
        mode: 0644
      when: authorized_keys.stat.exists

    - name: Update cronjob
      include_tasks: tasks/cronjob.yml

    - name: Set alsa volume to 80%
      become: yes
      command: amixer sset Digital 80%

    - name: Store alsa values
      become: yes
      command: alsactl store
